---
- hosts: web01
  become: yes
 
  tasks: 
        - name: installing nginx
          apt: name=nginx state=present
          notify:
                 - restart nginx
  handlers:
           - name: restart nginx
            # shell: nohup /usr/sbin/service nginx restart &
             service: name=nginx state=started    

...
