---
- hosts: web01
  become: yes 
  order: sorted
 
  vars: 
       name: kick
       uid: 80192
       comment: test
  tasks:
        - name: user creating
          user: name={{name}} uid={{uid}}
          when: ansible_facts['os_family'] == "Debian"
...

